modLoader = "kotlinforforge"
loaderVersion = "[3.12.0,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "hexcasted"
version = "${version}"
displayName = "HexCasted"
authors = "TechTastic"
description = '''
A Hexcasting x Create Big Cannons Addon
'''
#logoFile = ""

[[dependencies.hexcasted]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcasted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcasted]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexcasted]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcasted]]
modId = "createbigcannons"
mandatory = true
versionRange = "[5.5.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexcasted]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.11.1,)"
ordering = "NONE"
side = "BOTH"
